### ISSUE TITLE
bootstrap scss example not working

### ISSUE THREAD

**Issue by withinsight** [axept/prejss-cli#1]
I'm encountering an error when attempting to run the example code against Bootstrap:

```
prejss-cli bootstrap/v4-dev/scss/**/*.scss --parser postcss --out-dir ./bootstrap4-jss \
  --config plugins=postcss-import,postcss-simple-vars,postcss-sassy-mixins
```

Here's the error message:

```

repos/jss-test/node_modules/postcss/lib/processor.js:167
        throw new Error(i + ' is not a PostCSS plugin');
        ^

Error: @mixin alert-variant($background, $border, $color) {
  color: $color;
  @include gradient-bg($background);
  border-color: $border;

  hr {
    border-top-color: darken($border, 5%);
  }

  .alert-link {
    color: darken($color, 10%);
  }
}
 is not a PostCSS plugin
    at Processor.normalize (repos/jss-test/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (repos/jss-test/node_modules/postcss/lib/processor.js:54:25)
    at postcss (repos/jss-test/node_modules/postcss/lib/postcss.js:73:10)
    at exports.default (repos/jss-test/node_modules/prejss-cli/lib/process-file.js:35:16)
    at repos/jss-test/node_modules/prejss-cli/lib/cli.js:125:31
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (repos/jss-test/node_modules/prejss-cli/lib/cli.js:117:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jss-test@1.0.0 compile-bootstrap-v4: `prejss-cli node_modules/bootstrap/scss/**/*.scss --parser postcss --out-dir ./bootstrap4-jss --config plugins=postcss-import,postcss-simple-vars,postcss-sassy-mixins`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jss-test@1.0.0 compile-bootstrap-v4 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2018-08-08T19_53_00_704Z-debug.log
```

**Comment by Chochek** [comment]
I'm having the same issue. Any updates?
